models_config: config/models.yaml

persona: config/personas/student_yoo_grounded.yaml

scenarios:
  - config/scenarios/visual_consistency.yaml

target_models:
  -  gpt-4o-mini

evaluators:
  - visual_consistency

evaluator_kwargs:
  visual_consistency:
    reference_avatar_path: assets/personas/student_yoo.png

repeats: 5

output_dir: results_new/visual_consistency/student_yoo_test